[14.0][ADD] pos_return_voucher
aurestic/pos pull request #9
Opened 2023-05-04 06:20 UTC by zamberjo

2023-05-04 11:04 UTC, JordiToledo approved these changes

2023-05-04 12:00 UTC, almumu requested changes
faltarían los ondeletes en los many2one

2023-05-04 13:58 UTC, almumu approved these changes

2023-05-05 08:21 UTC, merged

2023-05-10 05:49 UTC, zamberjo commented
Hago un drop del commit del merge, para crear un nuevo PR ya que se han arreglado errores en el PR de la OCA.